pool:
  vmImage: 'ubuntu-18.04'

trigger:
  branches:
    include:
      - master  # Corrected trigger definition

steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'  # Fixed the unclosed quote
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/Templates'

  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install --production'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(build.artifactstagingdirectory)'
      artifact: 'drop'
      publishLocation: 'pipeline'  # Removed extra double quote
